"""Added rentals table

Revision ID: 6a40e28a9861
Revises: 
Create Date: 2025-03-12 18:50:01.047752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a40e28a9861'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentals',
    sa.Column('rental_id', sa.UUID(), nullable=False),
    sa.Column('lister_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('price', postgresql.MONEY(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='rental_status'), nullable=False),
    sa.ForeignKeyConstraint(['lister_id'], ['app_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rental_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentals')
    # ### end Alembic commands ###
